exports_files(["object_detection_football.onnx"])

filegroup(
    name = "object_detection_football",
    srcs = [
        "object_detection_football.onnx",
        "object_detection_football_int8.engine",
    ],
    visibility = ["//visibility:public"],
)
